---
title: "ASM_TE"
author: "DP"
date: "2024-07-27"
---
## load packages
```{r}
library("data.table")
library("tidyverse")
library("dplyr")
library("reshape2")
library("ggplot2")
library("ggthemes")
library('ggpubr')
library("RColorBrewer")
```
## Load data
```{r}
## Load RNA, Ribo paternal ratio df
RNA_paternal_ratio = read.csv("/Users/dayeapark/Desktop/Script_upload/datasets/processed_data/RNA_paternal_ratio.csv")
Ribo_paternal_ratio = read.csv("/Users/dayeapark/Desktop/Script_upload/datasets/processed_data/Ribo_paternal_ratio.csv")
long_read_allele_count = read.csv("/Users/dayeapark/Desktop/Script_upload/datasets/processed_data/long_read_allele_count.csv")

## Moditifation ratio df
step6_prob85 = read.csv("/Users/dayeapark/Desktop/Script_upload/datasets/processed_data/step6_prob85.Rdata")

## ASM sites
fdr_ASM23 = read.csv("/Users/dayeapark/Desktop/Script_upload/datasets/processed_data/fdr_ASM23.csv")

```
############ Allele specific expression analysis ################
## Label allele-bias to paternal ratio df 
```{r}
ASM_modratio_dif = step6_prob85[step6_prob85$Gene %in% fdr_ASM23$Gene ,c("gene", "rep1_alt_mod_ratio", "rep1_ref_mod_ratio", "rep2_alt_mod_ratio", "rep2_ref_mod_ratio")]

ASM_modratio_dif$rep1_mod_dif = ASM_modratio_dif$rep1_ref_mod_ratio - ASM_modratio_dif$rep1_alt_mod_ratio
ASM_modratio_dif$rep2_mod_dif = ASM_modratio_dif$rep2_ref_mod_ratio - ASM_modratio_dif$rep2_alt_mod_ratio

ASM_modratio_dif$dif_mean = (ASM_modratio_dif$rep1_mod_dif + ASM_modratio_dif$rep2_mod_dif ) /2

REF = ASM_modratio_dif[ASM_modratio_dif$dif_mean > 0,]$gene
ALT = ASM_modratio_dif[ASM_modratio_dif$dif_mean < 0,]$gene

## ASM label 
ASM_label <- function (df) { 
  df$ASM = "non-ASM"
  df[df$gene %in% unique(ASM_modratio_dif$gene), ]$ASM <- "ASM"
  
  df$ASM_bias <- "none"
  df[df$gene %in% REF, ]$ASM_bias <- "B6 bias"
  df[df$gene %in% ALT, ]$ASM_bias <- "CAST bias"
  return(df)
  }


```

## PLOT: longread, shortread seq and ribo-seq allele-specific expression ratio
## Longread/shortread/ribo paternal ratio
```{r}
## long-read 
LONG_read_count = long_read_allele_count[long_read_allele_count$gene %in% ASM_modratio_dif$gene,]

LONG_pat_ratio = LONG_read_count %>%
                    group_by(gene) %>% 
                    summarise( rep1_alt_sum = sum(rep1_alt),
                               rep1_ref_sum = sum(rep1_ref),
                               rep2_alt_sum = sum(rep2_alt),
                               rep2_ref_sum = sum(rep2_ref))

LONG_pat_ratio$long_rep1_pat_ratio = LONG_pat_ratio$rep1_alt_sum / (LONG_pat_ratio$rep1_ref_sum + LONG_pat_ratio$rep1_alt_sum)
LONG_pat_ratio$long_rep2_pat_ratio = LONG_pat_ratio$rep2_alt_sum / (LONG_pat_ratio$rep2_ref_sum + LONG_pat_ratio$rep2_alt_sum)

Longread_paternal_ratio = ASM_label(LONG_pat_ratio[,c(1,6,7)])
RNA_paternal_ratio_ASM = ASM_label(RNA_paternal_ratio)
Ribo_paternal_ratio_ASM = ASM_label(Ribo_paternal_ratio)

```

## revision, scatter plot (Fig 6A, updated, 062824)
```{r}
# df reframe 
df_reframe_ASE_ASM <- function (df) { 
  ASE_rep1 = df[df$ASM == "ASM", c(1,2,5)]
  ASE_rep2 = df[df$ASM == "ASM", c(1,3,5)]
  ASE_ASM_rep1 = merge(ASE_rep1, ASM_modratio_dif[,c("gene", "rep1_alt_mod_ratio","rep1_ref_mod_ratio")], by = "gene")
  ASE_ASM_rep2 = merge(ASE_rep2, ASM_modratio_dif[,c("gene", "rep2_alt_mod_ratio","rep2_ref_mod_ratio")], by = "gene")
  
  ASE_ASM_rep1$rep = "rep1"
  ASE_ASM_rep2$rep = "rep2"
  
  colnames(ASE_ASM_rep1) = colnames(ASE_ASM_rep2) = c("gene", "ASE_ratio",  "ASM_bias", "CAST_mod_ratio", "B6_mod_ratio", "rep")
  
  ASE_ASM_all_rep = rbind(ASE_ASM_rep1, ASE_ASM_rep2)
  
  ASE_ASM_all_rep$ASM_bias_new = "none"
  ASE_ASM_all_rep[ASE_ASM_all_rep$CAST_mod_ratio > ASE_ASM_all_rep$B6_mod_ratio ,]$ASM_bias_new <- "CAST-biased"
  ASE_ASM_all_rep[ASE_ASM_all_rep$CAST_mod_ratio < ASE_ASM_all_rep$B6_mod_ratio ,]$ASM_bias_new <- "B6-biased"
  
  return (ASE_ASM_all_rep)
}
  
revision_ASM_pat_ratio_scatter <- function (df, allele_pick, title_plot) { 
  df_ASE_ASM = df_reframe_ASE_ASM(df)

  df_ASE_ASM_select = df_ASE_ASM[ , c( "gene", "ASE_ratio",  "ASM_bias_new", "rep", allele_pick )]
  colnames(df_ASE_ASM_select) = c("gene", "ASE_ratio",  "ASM_bias", "rep", "allele_mod_ratio")
  ggplot(df_ASE_ASM_select) + 
  geom_point(aes(x = allele_mod_ratio, y = ASE_ratio, shape = rep, color =ASM_bias), 
             #position = position_jitterdodge(1), 
             alpha=0.8,
             size = 2.5)+
  #geom_hline(yintercept= 0.5, linetype="dashed", color = "red", size=0.2) + 
  theme_classic() +
  theme(legend.position="none") + 
  #theme(legend.position="top") + 
  ggtitle (title_plot) 
}

long_all <- ggarrange(
    revision_ASM_pat_ratio_scatter(Longread_paternal_ratio, "CAST_mod_ratio", "CAST_mod_ratio"),
    revision_ASM_pat_ratio_scatter(Longread_paternal_ratio, "B6_mod_ratio", "B6_mod_ratio"),
    nrow = 1)

short_all <- ggarrange(
    revision_ASM_pat_ratio_scatter(RNA_paternal_ratio_ASM, "CAST_mod_ratio", "CAST_mod_ratio"),
    revision_ASM_pat_ratio_scatter(RNA_paternal_ratio_ASM, "B6_mod_ratio", "B6_mod_ratio"),
    nrow = 1)
  
ribo_all <- ggarrange(
    revision_ASM_pat_ratio_scatter(Ribo_paternal_ratio_ASM, "CAST_mod_ratio", "CAST_mod_ratio"),
    revision_ASM_pat_ratio_scatter(Ribo_paternal_ratio_ASM, "B6_mod_ratio", "B6_mod_ratio"),
    nrow = 1)

ggarrange(long_all, short_all, ribo_all, nrow = 3, ncol = 1)

```

## stats 
```{r}
Longread_pat_ASE_ASM = df_reframe_ASE_ASM(Longread_paternal_ratio)

wilcox.test(Longread_pat_ASE_ASM[Longread_pat_ASE_ASM$ASM_bias_new == "CAST-biased",]$ASE_ratio,
            Longread_pat_ASE_ASM[Longread_pat_ASE_ASM$ASM_bias_new == "B6-biased",]$ASE_ratio)
```

## ( alt mod - ref mod ) add a regression line
```{r}
revision_ASM_dif_pat_ratio_scatter <- function (df, title_plot, ymin, ymax) { 
  df_ASE_ASM = df_reframe_ASE_ASM(df)
  df_ASE_ASM$mod_dif = df_ASE_ASM$CAST_mod_ratio - df_ASE_ASM$B6_mod_ratio
  ggplot(df_ASE_ASM) +
  geom_point(aes(x = mod_dif, y = ASE_ratio, shape = rep, color =ASM_bias_new),
             alpha=0.8,
             size = 2.5)+
  ggtitle (title_plot) +
  theme_classic() + 
  #theme(legend.position="top") +
  theme(legend.position="none") +  
  scale_x_continuous(limits = c(-1, 1)) + 
  scale_y_continuous(limits = c(ymin, ymax)) + 
  geom_hline(yintercept= 0.5, linetype="dashed", color = "red", size=0.2) +
  geom_smooth(aes(x = mod_dif, y = ASE_ratio), method = "lm", se = FALSE, color=  "darkgray")
}

dif_long1 <- revision_ASM_dif_pat_ratio_scatter(Longread_paternal_ratio, "longread_mod_ratio",0,1)
dif_short1 <- revision_ASM_dif_pat_ratio_scatter(RNA_paternal_ratio_ASM, "shortread_mod_ratio", 0,1)
dif_ribo1 <- revision_ASM_dif_pat_ratio_scatter(Ribo_paternal_ratio_ASM, "Ribo_mod_ratio",0,1)

dif_long2 <- revision_ASM_dif_pat_ratio_scatter(Longread_paternal_ratio, "longread_mod_ratio", 0.3,0.8)
dif_short2 <- revision_ASM_dif_pat_ratio_scatter(RNA_paternal_ratio_ASM, "shortread_mod_ratio", 0.3,0.8)
dif_ribo2 <- revision_ASM_dif_pat_ratio_scatter(Ribo_paternal_ratio_ASM, "Ribo_mod_ratio", 0.3,0.8)

merge_dif_mod = ggarrange(dif_long1, dif_short1, dif_ribo1,
                          dif_long2, dif_short2, dif_ribo2,
                          nrow = 2, ncol =3 )


revision_ASM_dif_pat_ratio_mean <- function (df, title_plot, ymin, ymax) { 
  df_ASE_ASM = df_reframe_ASE_ASM(df)
  df_ASE_ASM$mod_dif = df_ASE_ASM$CAST_mod_ratio - df_ASE_ASM$B6_mod_ratio
  ggplot(df_ASE_ASM) +
  geom_boxplot(aes(x = ASM_bias, y = ASE_ratio))+
  ggtitle (title_plot) +
  theme_classic() + 
  #theme(legend.position="top") +
  theme(legend.position="none") +
  scale_y_continuous(limits = c(ymin, ymax)) + 
  geom_hline(yintercept= 0.5, linetype="dashed", color = "red", size=0.2) 
}

dif_long_box <- revision_ASM_dif_pat_ratio_mean(Longread_paternal_ratio, "longread_mod_ratio", 0.3,0.8)
dif_short_box <- revision_ASM_dif_pat_ratio_mean(RNA_paternal_ratio_ASM, "shortread_mod_ratio", 0.3,0.8)
dif_ribo_box <- revision_ASM_dif_pat_ratio_mean(Ribo_paternal_ratio_ASM, "Ribo_mod_ratio", 0.3,0.8)

merge_dif_box = ggarrange(dif_long_box, dif_short_box, dif_ribo_box, nrow = 1, ncol =3 )

merge_all <- ggarrange(dif_long1, dif_short1, dif_ribo1,
                       dif_long2, dif_short2, dif_ribo2,
                       dif_long_box, dif_short_box, dif_ribo_box,
                          nrow = 3, ncol =3 )
merge_all


```
